"""
CredX - AI Credit Copilot Router
Provides dynamic conversational Q&A explaining score results using Gemini 2.5 Flash.
"""

import json
from fastapi import APIRouter, Body
from typing import Dict, Any, List
from src.genai.gemini_advisor import get_advisor

router = APIRouter(prefix="/api", tags=["AI Copilot"])


@router.post("/copilot")
@router.post("/v1/copilot")
def ask_copilot(payload: Dict[str, Any] = Body(...)):
    """
    AI Credit Copilot — answers user questions about their CredX credit profile.
    Uses Gemini 2.5 Flash for dynamic contextual LLM generation with fallback.
    """
    question = payload.get("question", "").strip()
    score_context = payload.get("score_context", {})

    if not question:
        return {
            "answer": "Please ask a question about your alternative credit score.",
            "key_points": [],
            "is_ai_generated": False,
            "disclaimer": "CredX AI Copilot explanation."
        }

    credx_score = score_context.get("credx_score", 700)
    risk_band = score_context.get("risk_band", "Medium")
    sub_scores = score_context.get("sub_scores", {})
    positives = [p.get("feature_label") for p in score_context.get("top_positive_contributors", []) if p.get("feature_label")]
    negatives = [n.get("feature_label") for n in score_context.get("top_negative_contributors", []) if n.get("feature_label")]

    advisor = get_advisor()
    
    if advisor.client:
        prompt = f"""
You are the CredX AI Credit Copilot. Answer the user's question empathetically, accurately, and concisely based on their credit assessment.

User Question: "{question}"

Applicant Credit Context:
- CredX Score: {credx_score} / 900
- Risk Category: {risk_band} Risk
- Income Stability Sub-score: {sub_scores.get('income_stability', 75)} / 100
- Payment Reliability Sub-score: {sub_scores.get('payment_reliability', 80)} / 100
- Digital Trust Sub-score: {sub_scores.get('digital_behaviour', 70)} / 100
- Top Strengths: {', '.join(positives) if positives else 'Income consistency'}
- Top Weaknesses/Risks: {', '.join(negatives) if negatives else 'Payment delays'}

Respond in strict JSON with:
{{
  "answer": "A clear, helpful 2-3 sentence answer specifically addressing the user question using their score context.",
  "key_points": ["Key action or takeaway 1", "Key action or takeaway 2", "Key action or takeaway 3"]
}}
"""
        try:
            res = advisor.client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
                config={"response_mime_type": "application/json"}
            )
            if res and res.text:
                parsed = json.loads(res.text)
                return {
                    "answer": parsed.get("answer", "Here is your credit health analysis."),
                    "key_points": parsed.get("key_points", []),
                    "is_ai_generated": True,
                    "disclaimer": "Generated by Gemini 2.5 Flash AI Copilot."
                }
        except Exception as e:
            print(f"Copilot Gemini call notice: {e}")

    # Smart contextual fallback if Gemini client is unavailable
    q_lower = question.lower()
    if "why" in q_lower or "reason" in q_lower:
        answer = (
            f"Your CredX score of {credx_score} ({risk_band} Risk) reflects your alternative financial behavior. "
            f"Your score is primarily driven by your income stability ({sub_scores.get('income_stability', 75)}/100) "
            f"and payment reliability ({sub_scores.get('payment_reliability', 80)}/100)."
        )
        key_points = [
            f"Strengths: {positives[0] if positives else 'Income consistency'}",
            f"Area for growth: {negatives[0] if negatives else 'Utility payment timing'}",
            "Alternative data rewards consistent monthly bill payment patterns."
        ]
    elif "improve" in q_lower or "increase" in q_lower or "boost" in q_lower:
        answer = (
            f"To boost your score from {credx_score}, focus on strengthening your lowest pillar: "
            f"Payment Reliability ({sub_scores.get('payment_reliability', 80)}/100). On-time utility bill settlements "
            "directly raise your score within 30 to 60 days."
        )
        key_points = [
            "Pay all utility and rental bills on or before due dates.",
            "Maintain steady UPI transaction history month over month.",
            "Avoid multi-day payment delays to preserve reliability score."
        ]
    elif "hurt" in q_lower or "negative" in q_lower or "weak" in q_lower:
        answer = (
            f"For your profile, the primary factors holding your score at {credx_score} are: "
            f"{', '.join(negatives) if negatives else 'occasional payment delays and cash-flow variance'}."
        )
        key_points = [
            "Payment delays beyond due dates lower your payment reliability sub-score.",
            "Failed or bounced payments create strong negative SHAP impacts."
        ]
    else:
        answer = (
            f"Based on your CredX score of {credx_score} ({risk_band} Risk), your financial activity demonstrates "
            f"a solid baseline. Your top strength is {positives[0] if positives else 'income consistency'}."
        )
        key_points = [
            f"Current Score: {credx_score} / 900",
            f"Primary Strength: {positives[0] if positives else 'Consistent deposits'}",
            "Consistently paying bills on time will unlock higher credit readiness."
        ]

    return {
        "answer": answer,
        "key_points": key_points,
        "is_ai_generated": True,
        "disclaimer": "Generated by CredX AI Copilot."
    }
